# brevis gateway, will post sig to here
bgw = "https://testnet-api.brevis.network"

# BLS key for eigenlayer
blspath = ""
blspwd = ""
# ecdsa for onchain tx, needed in join. after that not needed during normal operation
kspath = ""
kspwd = ""

# EigenLayer operator ID
operID = ""

# per chain config
[[multichain]]
chainID = 17000
name = "Holesky"
gateway = "https://ethereum-holesky-rpc.publicnode.com"
BlkInterval = 12
BlkDelay = 2
Brevis = "0xe0A61C0CAa3D8DE34bE6D31Bc4429ff1D51893A8"
BrvEigen = "0x7A46219950d8a9bf2186549552DA35Bf6fb85b1F"
BrvRegCo = "0x0dB4ceE042705d47Ef6C0818E82776359c3A80Ca"
AVSDir = "0x055733000064333CaDDbC92763c58BF0192fFeBf"
